### ISSUE TITLE
Add "per_page" value to the injector

### ISSUE THREAD

**Issue by luisherranz** [worona/wordpress-pwa#9]

**Comment by Poliuk** [comment]
> https://developer.wordpress.org/reference/functions/get_option/
>`posts_per_page` – _Maximum number of posts to show on a page; set in Reading Options._

`get_option( "post_per_page") `

**Comment by Poliuk** [comment]
@luisherranz `per_page` is now available as a JS variable. I didn't use it inside the injector, I let you close this issue once you decide how to proceed :)
